### ISSUE TITLE
建议换个名字

### ISSUE THREAD

**Issue by TomCC7** [thep0y/fcitx5-themes#1]
皮肤很好看  换个名字的话会更方便搜索和分享

**Comment by thep0y** [comment]
这我还真没想过，但换了名字后，很多人可能就不知道这是fcitx5的皮肤了，能提个两全其美的建议吗？

**Comment by TomCC7** [comment]
emm可能可以把fcitx5当成后缀？或者写简介里应该也能搜到的

**Comment by winjeg** [comment]
很不错， 有想法
