### ISSUE TITLE
本仓库正式更名为——烛光

### ISSUE THREAD

**Issue by thep0y** [thep0y/fcitx5-themes#10]
皮肤主色调为暗色，烛光有暗中取亮之意，故未来不会添加其他亮色皮肤，已有的 macOS Light 也不会删除。

**Comment by jinzhongjia** [comment]
请问一下，这个仓库的license是什么呢
我看并没有设置，我在尝试将这个主题打包至aur，需要填一下license
目前已经打包到了 AUR: [fcitx5-themes-candlelight](https://aur.archlinux.org/packages/fcitx5-themes-candlelight)

**Comment by thep0y** [comment]
> 请问一下，这个仓库的license是什么呢 我看并没有设置，我在尝试将这个主题打包至aur，需要填一下license 目前已经打包到了 AUR: [fcitx5-themes-candlelight](https://aur.archlinux.org/packages/fcitx5-themes-candlelight)

已添加 license
