### ISSUE TITLE
在fcitx5-rime下”高亮文字颜色“和”高亮背景颜色“配置不正确

### ISSUE THREAD

**Issue by chenxiex** [thep0y/fcitx5-themes#3]
按照主题颜色应该是文字白色、背景黑色。现在是文字黑色、背景白色。

**Comment by thep0y** [comment]
你能重新组织一下语言吗？如果不是本主题的问题，请到 fcitx5 仓库提问

**Comment by chenxiex** [comment]
> 你能重新组织一下语言吗？如果不是本主题的问题，请到 fcitx5 仓库提问

抱歉，可能是我没说明白。
我用的是manjaro stable+fcitx5-rime，在按照readme安装了本主题后，切换到winter主题，显示效果是这样的：
![IMG_20220101_213747_edit_7058125209859](https://user-images.githubusercontent.com/28776935/147851987-27ef8e0b-3e67-4ab8-943a-d9e0fd7f8e22.jpg)
显示拼音的地方背景是白色的，而本来应该是这样的：
![IMG_20220101_214559_edit_7467711726463](https://user-images.githubusercontent.com/28776935/147852022-8437bd8a-36ae-4239-ba30-2d9a2ffa45c6.jpg)
经查，问题处在这两个选项：
![Screenshot_20220101_214550](https://user-images.githubusercontent.com/28776935/147852085-cc75301a-67fc-4037-b2cf-6b81f8f964ed.png)
这里的“高亮文字颜色”应该是白色，而“高亮背景颜色”应该是黑色。

**Comment by thep0y** [comment]
> 显示拼音的地方背景是白色的

你用的是双行输入，我没有调整双行输入的效果，我自己用的是单行输入（预编辑模式），所以没有注意过此问题。
如果你解决了此问题，请提交一个pr进行合并

**Comment by thep0y** [comment]
https://github.com/thep0y/fcitx5-themes/commit/452286a21db617a80fbed9c02f3dff9d77632191
