### ISSUE TITLE
cp: 无法创建目录 '/root/.local/share/fcitx5/themes': 没有那个文件或目录

### ISSUE THREAD

**Issue by LanYunDev** [thep0y/fcitx5-themes#4]
cp: 无法创建目录 '/root/.local/share/fcitx5/themes': 没有那个文件或目录
<img width="656" alt="image" src="https://user-images.githubusercontent.com/95263282/168053442-0510a3f0-5c9d-4682-b479-17480a1e02ff.png">

**Comment by feiyu215** [comment]
没有可以自己创建一个，但路径要准确。还有就是确保安装了fcitx5。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月12日 18:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [thep0y/fcitx5-themes] cp: 无法创建目录 '/root/.local/share/fcitx5/themes': 没有那个文件或目录 (Issue #4) |

cp: 无法创建目录 '/root/.local/share/fcitx5/themes': 没有那个文件或目录

**Comment by LanYunDev** [comment]
好的,我试试

**Comment by LanYunDev** [comment]
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/95263282/168054992-9258d586-db28-4abb-b471-e46bbb247baa.png">
如何生效呢?配置目录是我手动mkdir生成的

**Comment by LanYunDev** [comment]
我已经重启过,依然没有生效

**Comment by LanYunDev** [comment]
问题解决,路径问题,我设置为默认root账户,所以~指的是/root,而正确的路径应该为/home/lanyun
<img width="654" alt="image" src="https://user-images.githubusercontent.com/95263282/168059977-bf85e122-8c17-4309-971a-38dfed927e11.png">

**Comment by feiyu215** [comment]
还有，我安装的时候就是用当前账户的目录，并没有进root账户。再就是~/默认就是当前账户的用户目录。不知道你的为什么会有那样的提示。其实过程很简单，所有的fcitx5主题都可以放在那个目录下面。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月12日 18:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [thep0y/fcitx5-themes] cp: 无法创建目录 '/root/.local/share/fcitx5/themes': 没有那个文件或目录 (Issue #4) |

cp: 无法创建目录 '/root/.local/share/fcitx5/themes': 没有那个文件或目录
