### ISSUE TITLE
建议能够增加一个类苹果输入法的主题.

### ISSUE THREAD

**Issue by LanYunDev** [thep0y/fcitx5-themes#5]
建议能够增加一个类苹果输入法的主题.个人认为比较好看.
<img width="440" alt="image" src="https://user-images.githubusercontent.com/95263282/168060710-b9b90a37-a264-4781-b852-fdd1b0c023ec.png">
<img width="421" alt="image" src="https://user-images.githubusercontent.com/95263282/168060844-ee134c44-1e5d-423f-bf95-dd65bd13b456.png">
(希望也能考虑考虑深色模式...

**Comment by feiyu215** [comment]
这个主题不是我开发的，这个我好像只是收藏了吧。你从哪里看到的。我并不是开发者。😥😥😥



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月12日 19:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [thep0y/fcitx5-themes] 建议能够增加一个类苹果输入法的主题. (Issue #5) |

建议能够增加一个类苹果输入法的主题.个人认为比较好看.


(希望也能考虑考虑深色模式...

**Comment by LanYunDev** [comment]
> 这个主题不是我开发的，这个我好像只是收藏了吧。你从哪里看到的。我并不是开发者。😥😥😥
> […](#)

<img width="325" alt="image" src="https://user-images.githubusercontent.com/95263282/168062968-c1459bb5-9fdf-4c01-82e5-b7fa698328c2.png">
你可能点击了Watch而收到邮件📧

**Comment by feiyu215** [comment]
都是英语不好惹的祸，这个网站我还没有完全搞明白怎么用，也不经常用，因为有时候无法登录。抱歉。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月12日 19:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [thep0y/fcitx5-themes] 建议能够增加一个类苹果输入法的主题. (Issue #5) |

这个主题不是我开发的，这个我好像只是收藏了吧。你从哪里看到的。我并不是开发者。😥😥😥
…

你可能点击了Watch而收到邮件📧

**Comment by thep0y** [comment]
等我有闲功夫且有心情时才可能会看看能不能写，如果你能提交pr我觉得会更好。

**Comment by cangkui** [comment]
我在网上找了个比较像的，自己改了改圆角感觉还行，不知道这个候选的形式怎么从 1. xxx  2. xxx  3. xxx 变成 1 xxx  2 xxx  3 xxx，另外，这个主题的背景都是用svg图片实现的，背面的白色背景好像样式也不太对。[原地址](https://auok.run/archives/10)

![2023-09-15_00-25.png](https://www.z4a.net/images/2023/09/15/2023-09-15_00-25.png)

允许提交PR么？

**Comment by thep0y** [comment]
> 我在网上找了个比较像的，自己改了改圆角感觉还行，不知道这个候选的形式怎么从 1. xxx 2. xxx 3. xxx 变成 1 xxx 2 xxx 3 xxx，另外，这个主题的背景都是用svg图片实现的，背面的白色背景好像样式也不太对。[原地址](https://auok.run/archives/10)
> 
> ![2023-09-15_00-25.png](https://camo.githubusercontent.com/8f9004d74a85c78335fac56c835079e6955cbdfe077030829be15234cf76edfd/68747470733a2f2f7777772e7a34612e6e65742f696d616765732f323032332f30392f31352f323032332d30392d31355f30302d32352e706e67)
> 
> 允许提交PR么？

可以提交pr

**Comment by thep0y** [comment]
仿mac主题已添加，如需改进请提交pr。

**Comment by JadeVane** [comment]
> 不知道这个候选的形式怎么从 1. xxx 2. xxx 3. xxx 变成 1 xxx 2 xxx 3 xxx

请问解决了吗，这个皮肤在 ubuntu 22.04 上用起来完全不是一个样，不知是哪里有问题

![图片](https://github.com/thep0y/fcitx5-themes/assets/34258753/41ab34aa-4e28-47cd-8e39-12b5a6e0c3a2)

**Comment by thep0y** [comment]
> > 不知道这个候选的形式怎么从 1. xxx 2. xxx 3. xxx 变成 1 xxx 2 xxx 3 xxx
> 
> 请问解决了吗，这个皮肤在 ubuntu 22.04 上用起来完全不是一个样，不知是哪里有问题

皮肤只提供输入框和候选区样式，候选字标签和候选字样式不是由皮肤控制，而是由输入引擎控制。

从你的截图中可以看出来，字体相对输入框较小，需要适当增加字体尺寸或减小输入框高度。

至于标签后面的“.”，你需要查阅你使用的输入法的相关文档，不过需要注意的是，fcitx5 不是输入法，而是一个输入法框架，fcitx5-pinyin 这种才是具体的输入法实现，据我所知这些输入法中 fcitx5-rime 是没有“.“的，同时也是 README 截图中的效果。

**Comment by JadeVane** [comment]
感谢解答！我去试试

**Comment by thep0y** [comment]
> 感谢解答！我去试试

你使用双拼，更建议你使用 fcitx5-rime，切换和定制码表非常自由，不需要因为使用不同的输入方案而安装多个输入法。

fcitx5-rime 支持的输入方案包括但不限于：

- 双拼
- 全拼
- 五笔
- 郑码
- 仓颉 

但云输入、智能纠错不支持。
