### ISSUE TITLE
输入框过大

### ISSUE THREAD

**Issue by shenmo7192** [thep0y/fcitx5-themes#6]
![图片](https://user-images.githubusercontent.com/47873776/191000118-3914cfcb-2e1c-461a-b356-9fd85f5b732c.png)
比文字都大了

**Comment by thep0y** [comment]
你可以开启单行模式，双行我基本不用，所以不会调整样式。发自我的手机-------- 原始邮件 --------发件人： shenmo ***@***.***>日期： 2022年9月19日周一 18:39收件人： thep0y/fcitx5-themes ***@***.***>抄送： Subscribed ***@***.***>主    题： [thep0y/fcitx5-themes] 输入框过大 (Issue #6)



比文字都大了

**Comment by shenmo7192** [comment]
我不知怎么，现在我的fcitx5无法读取dpi,一直是一倍缩放
我调试了一下午，都没能成功修复
这时候我想起这个皮肤了
正好，对我来说过大的输入框在未被缩放的情况下刚刚好
非常感谢！
